/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.san.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.san.domain.Users;
import com.san.service.imp.UserServiceImp;
import com.san.service.inter.UserServiceInter;
import com.san.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2017
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	/**
	 * 响应登陆请求
	 * @throws Exception 
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		UserForm uf=(UserForm)form;
//		UserServiceImp us=new UserServiceImp();
		//通过接口调用
		UserServiceInter usit=new UserServiceImp();
		Users u=new Users();
		u.setUsername(uf.getUsername());
		u.setPassword(uf.getPassword());
		if(usit.checkUser(u)!=null){
			Users user=usit.checkUser(u);
			request.getSession().setAttribute("user", user);
			return mapping.findForward("loginOk");
		}else{
			return mapping.findForward("reLogin");
		}
//		if((uf.getPassword()).equals("123")){
//			return mapping.findForward("loginOk");
//		}else{
//			return mapping.findForward("reLogin");
//		}
	}
	/**
	 * 响应退出请求
	 */
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		request.getSession().invalidate();//清空Session
		return mapping.findForward("reLogin");
	}
}